{% set header = "pygobject.h" %}
{% set pc = "pygobject-3.0" %}
{% set name = "pygobject" %}
{% set version = "3.40.1" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/{{ name }}/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 00c6d591f4cb40c335ab1fd3e8c17869ba15cfda54416fe363290af766790035

build:
  number: 2
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - cairo
    - glib
    - gobject-introspection
    - libffi
    - pycairo
    - python
  run:
    - gobject-introspection
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - pycairo
    - python

test:
  requires:
    - pkg-config
  imports:
    - gi
    - gi.repository.GLib
  commands:
    # verify that header gets installed and can be located through pkg-config
    {% set pc = "pygobject-3.0" %}
    {% set header = "pygobject.h" %}
    - test -f $PREFIX/include/{{ pc }}/{{ header }}  # [unix]
    - test -f `pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`/{{ header }}  # [unix]
    - if not exist %LIBRARY_INC%\\{{ pc }}\\{{ header }} exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ header }}" exit 1  # [win]


about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Python bindings for GObject Introspection

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - ryanvolz
    - sebastian-luna-valero
    - tschoonj
