{% set name = "pygobject" %}
{% set version = "3.38.0" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/{{ name }}/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 0372d1bb9122fc19f500a249b1f38c2bb67485000f5887497b4b205b3e7084d5
  patches:
    - macos-tests.patch
    - meson-rpaths.patch  # [linux]

build:
  number: 1
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-msys2-runtime  # [win]
    - ninja
    - {{ posix }}patch
    - {{ native }}pkg-config
  host:
    - glib
    - gobject-introspection
    - libffi
    - meson  # undiagnosed issues with meson in build prefix that go away when in host
    - pycairo
    - python
  run:
    - glib
    - gobject-introspection
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - libffi
    - pycairo
    - python

test:
  requires:
    - pkg-config
    - gtk3
  imports:
    - gi
    - gi.repository.GLib
    - gi.repository.Gtk
  commands:
    # verify that header gets installed and can be located through pkg-config
    {% set pc = "pygobject-3.0" %}
    {% set header = "pygobject.h" %}
    - test -f $PREFIX/include/{{ pc }}/{{ header }}  # [unix]
    - test -f `pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`/{{ header }}  # [unix]
    - if not exist %LIBRARY_INC%\\{{ pc }}\\{{ header }} exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ header }}" exit 1  # [win]

    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Python bindings for GObject Introspection'

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - sebastian-luna-valero
    - tschoonj
