{% set name = "pygobject" %}
{% set version = "3.42.2" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: ade8695e2a7073849dd0316d31d8728e15e1e0bc71d9ff6d1c09e86be52bc957

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - cairo
    - glib
    - gobject-introspection
    - libffi
    - pycairo
    - python
  run:
    - libgirepository
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - pycairo
    - python
    - ucrt  # [win]

test:
  requires:
    - pkg-config
  imports:
    - gi
    - gi.pygtkcompat
    - gi.repository.GLib
  commands:
    # verify that header gets installed and can be located through pkg-config
    - test -f $PREFIX/include/pygobject-3.0/pygobject.h  # [unix]
    - test -f `pkg-config --variable=pygobjectincludedir --dont-define-prefix pygobject-3.0`/pygobject.h  # [unix]
    - if not exist %LIBRARY_INC%\\pygobject-3.0\\pygobject.h exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=pygobjectincludedir --dont-define-prefix pygobject-3.0`) do if not exist "%%a/pygobject.h" exit 1  # [win]


about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Python bindings for GObject Introspection

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - ryanvolz
    - sebastian-luna-valero
    - tschoonj
